name: buf-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone target repository
        run: git clone https://github.com/lennysgarage/relations-client-java.git

      - name: Copy proto files
        run: |
          cp -r api/kessel/relations/v1/*.proto relations-client-java/src/main/proto/kessel/relations/v1/
          cp -r api/kessel/relations/v1beta1/*.proto relations-client-java/src/main/proto/kessel/relations/v1beta1/

      - name: Commit proto files
        run: |
          git config --global user.name "jonathan marcantonio"
          git config --global user.email "jmarcant@redhat.com"
          cd relations-client-java
          git checkout -b sync-proto-files
          git commit -am "Sync updated proto files"
          git push origin sync-proto-files

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Sync proto files
          branch: sync-proto-files  
          base: main 
