name: buf-push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "api"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "api"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1"
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "api"
          buf_token: ${{ secrets.BUF_TOKEN }}
      - name: Extract commit SHA
        id: extract-sha
        run: |
          echo "COMMIT_SHA=$(echo '${{ steps.buf-push.outputs.buf_push_output }}' | grep -o 'relations-api[^"]*' >> $GITHUB_OUTPUT
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: lennysgarage/relations-client-java
          event-type: api_update
          client-payload: '{"commit": "${{ steps.extract-sha.outputs.COMMIT_SHA }}"}'



